; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = m5stack-cores3

[env:m5stack-cores3]
platform = espressif32
framework = arduino
upload_speed = 2000000
monitor_speed = 115200
lib_deps =
    m5stack/M5Unified@^0.2.7
    m5stack/M5GFX@^0.2.13
    m5stack/M5CoreS3@^1.0.1
    https://github.com/esol-community/micro_ros_platformio#feature/rmw_zenoh_pico

board = m5stack-cores3
board_microros_distro = jazzy
board_microros_rmw_impl = rmw_zenoh_pico
board_microros_transport = unicast

build_flags =
    -DMICRO_ROS_TRANSPORT_UDP
    -DARDUINOJSON_ENABLE_ARDUINO_STRING=1
    -DARDUINOJSON_USE_LONG_LONG=1
    -DARDUINOJSON_DECODE_UNICODE=1
    -DARDUINOJSON_ENABLE_NAN=1
    -DUSE_RMW_ZENOH_PICO=1
    -DUSE_ROS_DOMAIN_ID=1
